In [3]:
import pandas as pd
import numpy as np

In [5]:
df = pd.read_csv('Reviews.csv')
df.head()

,Id,ProductId,UserId,ProfileName,HelpfulnessNumerator,HelpfulnessDenominator,Score,Time,Summary,Text
0,1,B001E4KFG0,A3SGXH7AUHU8GW,delmartian,1,1,5,1303862400,Good Quality Dog Food,I have bought several of the Vitality canned d...
1,2,B00813GRG4,A1D87F6ZCVE5NK,dll pa,0,0,1,1346976000,Not as Advertised,Product arrived labeled as Jumbo Salted Peanut...
2,3,B000LQOCH0,ABXLMWJIXXAIN,"Natalia Corres ""Natalia Corres""",1,1,4,1219017600,"""Delight"" says it all",This is a confection that has been around a fe...
3,4,B000UA0QIQ,A395BORC6FGVXV,Karl,3,3,2,1307923200,Cough Medicine,If you are looking for the secret ingredient i...
4,5,B006K2ZZ7K,A1UQRSCLF8GW1T,"Michael D. Bigham ""M. Wassir""",0,0,5,1350777600,Great taffy,Great taffy at a great price. There was a wid...

In [7]:
def label_sentiment(rating):
    if rating in [1, 2]:
        return 'negative'
    elif rating == 3:
        return 'neutral'
    elif rating in [4, 5]:
        return 'positive'
    else:
        return 'unknown'

df['sentiment'] = df['Score'].apply(label_sentiment)
result_df = df[['Text', 'Score', 'sentiment']]
result_df

                                                     Text  Score sentiment
0       I have bought several of the Vitality canned d...      5  positive
1       Product arrived labeled as Jumbo Salted Peanut...      1  negative
2       This is a confection that has been around a fe...      4  positive
3       If you are looking for the secret ingredient i...      2  negative
4       Great taffy at a great price.  There was a wid...      5  positive
...                                                   ...    ...       ...
568449  Great for sesame chicken..this is a good if no...      5  positive
568450  I'm disappointed with the flavor. The chocolat...      2  negative
568451  These stars are small, so you can give 10-15 o...      5  positive
568452  These are the BEST treats for training and rew...      5  positive
568453  I am very satisfied ,product is as advertised,...      5  positive

[568454 rows x 3 columns]

In [11]:
result_df.to_csv('labelled_reviews.csv', index=False)
print('Sentiment labels added and saved to labelled_reviews.csv')

Sentiment labels added and saved to labelled_reviews.csv